- name: Install packages
  become: true
  apt:
    state: present
    name:
      - mutt

- name: Create ~/.mutt directory
  file:
    path: ~/.mutt
    state: directory

- name: Place mutt configuration file
  template:
    src: muttrc
    dest: ~/.mutt/

- name: Create ~/.mutt/aliases file
  file:
    path: ~/.mutt/aliases
    state: file

- name: Install add_alias script
  copy:
    src: add_alias
    dest: ~/.mutt/
    mode: 0755
