- name: Install mutt
  become: true
  apt:
    state: present
    name: mutt

- name: Place mutt configuration file
  template:
    src: muttrc
    dest: /home/{{ ansible_user_id }}/.mutt/

- name: Create mutt aliases file
  file:
    path: /home/{{ ansible_user_id }}/.mutt/aliases
    state: file

- name: Automatically populate aliases
  copy:
    src: add_alias
    dest: /home/{{ ansible_user_id }}/.mutt/
    mode: 0755
