- name: Install DOSBox
  become: true
  apt:
    state: present
    name: dosbox

- name: Force 640x480 resolution
  become: true
  copy:
    src: 10-intel.conf
    dest: /etc/X11/xorg.conf.d/

- name: Install IA Launcher
  pip:
    name: ialauncher
    state: present

- name: Use IA Launcher as window manager
  copy:
    src: dotfiles/
    dest: /home/{{ ansible_user_id }}/
