#!/usr/bin/env ansible-playbook

# Execute this playbook as `./playbook.yml`

- hosts: all
  roles:
    - role: common
      tags: common

- hosts: webservers
  roles:
    - role: mailserver
      tags: mailserver
    - role: database
      tags: database
    - role: webserver
      tags: webserver

- hosts: workstations
  roles:
    - role: ssh
      tags: ssh
    - role: mailserver
      tags: mailserver
    - role: mailclient
      tags: mailclient
    - role: workstation
      tags: workstation
    - role: X
      tags: X
    - role: Xworkstation
      tags: Xworkstation

- hosts: gamestations
  roles:
    - role: X
      tags: X
    - role: gamestation
      tags: gamestation

- hosts: kiosks
  roles:
    - role: X
      tags: X

- hosts: laptops
  roles:
    - role: laptop
      tags: laptop
