#!/usr/bin/env ansible-playbook

- hosts: all
  roles:
    - role: common
      tags: common
    - role: mailserver
      tags: mailserver
    - role: database
      tags: database

- hosts: webservers
  roles:
    - role: webserver
      tags: webserver

- hosts: workstations
  roles:
    - role: ssh
      tags: ssh
    - role: mailclient
      tags: mailclient
    - role: workstation
      tags: workstation
    - role: X
      tags: X
    - role: Xworkstation
      tags: Xworkstation

- hosts: laptops
  roles:
    - role: laptop
      tags: laptop
