- name: Install graphical packages
  become: true
  apt:
    state: present
    name:
      - chromium
      - eog
      - evince
      - file-roller
      - ghc
      - libghc-xmonad-contrib-dev
      - mpv
      - network-manager-gnome
      - pavucontrol
      - pulseaudio
      - pulseaudio-module-zeroconf
      - rxvt-unicode
      - suckless-tools
      - thunar
      - trayer
      - webext-ublock-origin
      - x11-apps
      - x11-xserver-utils
      - xcalib
      - xclip
      - xfonts-terminus
      - xinit
      - xinput
      - xmonad

- block:
    - name: Install Firefox
      become: true
      apt:
        state: present
        name:
          - firefox
  rescue:
    - name: Install Firefox ESR instead
      become: true
      apt:
        state: present
        name:
          - firefox-esr

- name: Setup autologin for user {{ ansible_user_id }}
  become: true
  template:
    src: override.conf
    dest: /etc/systemd/system/getty@tty1.service.d/

- name: Enable bitmap fonts
  become: true
  file:
    path: /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf
    state: absent

- name: Xsession root background, root cursor, disable blanking
  become: true
  copy:
    src: Xsession.d/
    dest: /etc/X11/Xsession.d/

- name: Xresources for fonts, colors, and LCD hinting
  become: true
  copy:
    src: Xresources/
    dest: /etc/X11/Xresources/

- name: Bash profile to automatically start X
  become: true
  copy:
    src: profile.d/
    dest: /etc/profile.d/

- name: Set default terminal emulator to rxvt-unicode
  become: true
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvt

- name: PulseAudio Zeroconf
  become: true
  lineinfile:
    dest: /etc/pulse/default.pa
    line: load-module module-zeroconf-discover

- name: Copy graphical dotfiles
  become: true
  copy:
    src: dotfiles/
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    force: "{{ item.force }}"
  loop:
    - dest: /home/{{ ansible_user_id }}/
      owner: "{{ ansible_user_id }}"
      force: false
    - dest: /etc/skel/
      owner: root
      force: true
