- name: Install workstation packages
  become: true
  apt:
    state: present
    name:
      - ack
      - ansible
      - apt-file
      - bc
      - curl
      - emacs
      - jq
      - liblocal-lib-perl
      - pwgen
      - python3-dev
      - python3-pip
      - python3-venv
      - rbenv
      - texlive-latex-recommended
      - tidy
      - unzip
      - vim
      - w3m
      - whois

- name: Copy workstation dotfiles
  become: true
  copy:
    src: dotfiles/
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    force: "{{ item.force }}"
  loop:
    - dest: /home/{{ ansible_user_id }}/
      owner: "{{ ansible_user_id }}"
      force: false
    - dest: /etc/skel/
      owner: root
      force: true
