- name: Install database packages
  become: true
  apt:
    state: present
    name:
      - postgresql
      - postgresql-server-dev-all

- name: Passwordless database access for local users
  become: true
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/{{ item }}/main/
    owner: postgres
    mode: 0640
  notify: restart postgres
  loop:
    - 15
    - 16

- name: Daily database backups
  become: true
  copy:
    src: daily_backup
    dest: /etc/cron.daily
    mode: 0755

- name: Monthly database backups
  become: true
  copy:
    src: monthly_backup
    dest: /etc/cron.monthly
    mode: 0755
