- name: Fetch public ssh key
  command: cat ~/.ssh/id_rsa.pub
  register: public_key
  changed_when: false
  no_log: true

- name: Allow this host to access all others
  authorized_key:
    user: '{{ ansible_user_id }}'
    state: present
    key: '{{ public_key.stdout }}'
  delegate_to: '{{ item }}'
  loop: '{{ groups.all }}'
  failed_when: false
  ignore_unreachable: yes
  no_log: true

- name: Place SSH config file
  become: true
  template:
    src: 10-convenience
    dest: /etc/ssh/ssh_config.d/
