- name: Install laptop packages
  become: true
  apt:
    state: present
    name:
      - xbattbar
      - xbindkeys

- name: Trackpad, battery bar, multimedia keys
  become: true
  copy:
    src: Xsession.d/
    dest: /etc/X11/Xsession.d/

- name: Volume and brightness keys
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  loop:
    - volume
    - brightness

- name: Lid switch
  become: true
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: HandleLidSwitch=suspend
    line: HandleLidSwitch=suspend
    state: present

- name: Copy laptop dotfiles
  become: true
  copy:
    src: dotfiles/
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    force: "{{ item.force }}"
  loop:
    - dest: /home/{{ ansible_user_id }}/
      owner: "{{ ansible_user_id }}"
      force: false
    - dest: /etc/skel/
      owner: root
      force: true
