- name: Install graphical packages
  become: true
  apt:
    state: present
    name:
      - gimp
      - inkscape
      - libreoffice
      - xautolock
      - xss-lock
      - xtrlock

- name: Place Xsession configuration files
  become: true
  copy:
    src: Xsession.d/
    dest: /etc/X11/Xsession.d/
